vim.pack.add(require("config.plugins.spec"))

require("config.plugins.colorscheme")
require("config.plugins.multiplugin")
require("config.plugins.whichkey")
require("config.plugins.nvimtree")
require("config.plugins.telescope")
require("config.plugins.lazygit")

require("config.plugins.treesitter")
require("config.plugins.mason")
require("config.plugins.lsp")
require("config.plugins.cmp")
require("config.plugins.formatting")
require("config.plugins.linting")

require("config.plugins.trouble")
require("config.plugins.todo")
require("config.plugins.ufo")
require("config.plugins.git")
require("config.plugins.harpoon")
require("config.plugins.opencode")

require("config.plugins.markdown")
require("config.plugins.auto-session")
require("config.plugins.alpha")
require("config.plugins.lualine")
require("config.plugins.mini")

require("config.plugins.autosave")
