return {
    ensure_installed = {
        "bash",
        "c",
        "cpp",
        "dockerfile",
        "go",
        "json",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "printf",
        "python",
        "query",
        "rust",
        "toml",
        "vim",
        "vimdoc",
        "yaml",
    },
    auto_install = true,
    highlight = { enable = true },
    indent = { enable = true },
}
